spring:
  # Start For accessing protected endpoints by spring security
  security:
    user:
      name: ${SPRING_USER_NAME:user}
      password: ${SPRING_USER_PASSWORD:rahasia}
  # End line For accessing protected endpoints by spring security
  application:
    name: ${SPRING_APPLICATION_NAME:hogwarts_artifact_online}
  datasource:
    url: jdbc:h2:mem:hogwarts
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.h2.Driver
  # To show sql log
  jpa:
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  h2:
    console:
      enabled: true
api:
  endpoint:
    base-url: ${API_ENDPOINT_BASE_URL:/api/v1}
server:
  port: ${SERVER_PORT:8080}