spring:
  # Start For accessing protected endpoints by spring security
  security:
    user:
      name: user
      password: rahasia
  # End line For accessing protected endpoints by spring security
  application:
    name: hogwarts_artifact_online
  datasource:
    url: jdbc:h2:mem:hogwarts
    username: sa
    password:
    driver-class-name: org.h2.Driver
  # To show sql log
  jpa:
    show-sql: true
api:
  endpoint:
    base-url: /api/v1